# Generated by Django 3.2.18 on 2023-03-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tantargy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tantárgy',
                'verbose_name_plural': 'Tantárgyak',
            },
        ),
        migrations.CreateModel(
            name='Tanar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nev', models.CharField(max_length=100)),
                ('tantargyai', models.ManyToManyField(to='app_tanfelo.Tantargy')),
            ],
            options={
                'verbose_name': 'Tanár',
                'verbose_name_plural': 'Tanárok',
            },
        ),
    ]
